name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Runs the pipeline when a PR is opened against main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest  # Install linting and testing tools

      - name: Run linting
        run: |
          flake8 .  # Fails the pipeline if there are linting issues

      - name: Run tests
        run: |
          pytest --exitfirst --disable-warnings  # Fails the pipeline on first test failure

